const mongoose = require('mongoose');

const GarageSchema = new mongoose.Schema({
    garageId: { type: String, unique: true },
    name: { type: String, required: true },
    state: { type: String },
    district: { type: String },
    address: { type: String },
    coordinates: { type: String },           // e.g. "30.7333, 76.7794"
    type: { type: [String] },          // e.g. ['Petrol', 'Diesel', 'EV']
    rating: { type: Number, default: null },
    partner: { type: Boolean, default: false },
    isVerified: { type: Boolean, default: false },
    status: { type: String, default: 'Pending' },
    pickupDrop: { type: Boolean, default: false },
    ownerName: { type: String },
    ownerContact: { type: String },
    ownerEmail: { type: String },
    phone: { type: String },
    whatsapp: { type: String },
    garageContact: { type: String, default: '' },
    garageEmail: { type: String, default: '' },
    workingHours: { type: String },
    workingDays: { type: String },
    services: { type: String },
    panCard: { type: String, default: '' },
    adharCard: { type: String, default: '' },
    voterId: { type: String, default: '' },
    gstCert: { type: String, default: '' },
    agreement: { type: String, default: '' },
    signature: { type: String, default: '' },
    tradeLicense: { type: String, default: '' },
    panCardUploadedAt: { type: Date },
    adharCardUploadedAt: { type: Date },
    voterIdUploadedAt: { type: Date },
    gstCertUploadedAt: { type: Date },
    agreementUploadedAt: { type: Date },
    signatureUploadedAt: { type: Date },
    tradeLicenseUploadedAt: { type: Date },
    panCardDocId: { type: String, default: '' },
    adharCardDocId: { type: String, default: '' },
    voterIdDocId: { type: String, default: '' },
    gstCertDocId: { type: String, default: '' },
    agreementDocId: { type: String, default: '' },
    signatureDocId: { type: String, default: '' },
    tradeLicenseDocId: { type: String, default: '' },
    panCardStatus: { type: String, default: 'Pending' },
    adharCardStatus: { type: String, default: 'Pending' },
    voterIdStatus: { type: String, default: 'Pending' },
    gstCertStatus: { type: String, default: 'Pending' },
    agreementStatus: { type: String, default: 'Pending' },
    signatureStatus: { type: String, default: 'Pending' },
    tradeLicenseStatus: { type: String, default: 'Pending' },
    panCardHistory: { type: Array, default: [] },
    adharCardHistory: { type: Array, default: [] },
    voterIdHistory: { type: Array, default: [] },
    gstCertHistory: { type: Array, default: [] },
    agreementHistory: { type: Array, default: [] },
    signatureHistory: { type: Array, default: [] },
    tradeLicenseHistory: { type: Array, default: [] },
    panCardRemark: { type: String, default: '' },
    adharCardRemark: { type: String, default: '' },
    voterIdRemark: { type: String, default: '' },
    gstCertRemark: { type: String, default: '' },
    agreementRemark: { type: String, default: '' },
    signatureRemark: { type: String, default: '' },
    tradeLicenseRemark: { type: String, default: '' },
    gstNumber: { type: String, default: '' },
    sacCode: { type: String, default: '' },
    hsnCode: { type: String, default: '' },
    password: { type: String },

    resetPasswordOtp: { type: String },
    resetPasswordExpires: { type: Date },
    disabledServices: { type: [String], default: [] },
}, { timestamps: true });

module.exports = mongoose.model('Garage', GarageSchema);
